export default {

    // tab 特性
    public_trait_tab: '公共的',
    self_trait_tab: '我的',
    group_trait_tab: '运营组的',
    subordinate_trait_tab: '下级的',

    // 新建特性
    create_trait_button_public: '新建特性',
    create_trait_button_self: '新建特性',
    create_trait_button_group: '新建特性',
    create_trait_button_subordinate: '新建特性',
    // 激活特性
    active_trait_button_public: '激活特性',
    active_trait_button_self: '激活特性',
    active_trait_button_group: '激活特性',
    active_trait_button_subordinate: '激活特性',
    // 冻结特性
    freeze_trait_button_public: '冻结特性',
    freeze_trait_button_self: '冻结特性',
    freeze_trait_button_group: '冻结特性',
    freeze_trait_button_subordinate: '冻结特性',
    // 发布特性
    publish_trait_button_public: '发布特性',
    publish_trait_button_self: '发布特性',
    publish_trait_button_group: '发布特性',
    publish_trait_button_subordinate: '发布特性',
    // 删除特性
    delete_trait_button_public: '删除特性',
    delete_trait_button_self: '删除特性',
    delete_trait_button_group: '删除特性',
    delete_trait_button_subordinate: '删除特性',
    // 修改策略
    strategy_trait_button_public: '修改策略',
    strategy_trait_button_self: '修改策略',
    strategy_trait_button_group: '修改策略',
    strategy_trait_button_subordinate: '修改策略',
    // ...
    more_trait_button_public: '更多操作',
    more_trait_button_self: '更多操作',
    more_trait_button_group: '更多操作',
    more_trait_button_subordinate: '更多操作',
    // 描述...
    des_trait_button_public: '特性描述',
    des_trait_button_self: '特性描述',
    des_trait_button_group: '特性描述',
    des_trait_button_subordinate: '特性描述',
    // 特性名称
    name_trait_button_public: '特性名称',
    name_trait_button_self: '特性名称',
    name_trait_button_group: '特性名称',
    name_trait_button_subordinate: '特性名称',
    // 特性修改所属目录
    catalog_trait_cascader_public: '特性所属目录',
    catalog_trait_cascader_self: '特性所属目录',
    catalog_trait_cascader_group: '特性所属目录',
    catalog_trait_cascader_subordinate: '特性所属目录',
    // 特性目录增，删，改
    catalog_tree_trait_public: '特性目录增删改',
    catalog_tree_trait_self: '特性目录增删改',
    catalog_tree_trait_group: '特性目录增删改',
    catalog_tree_trait_subordinate: '特性目录增删改',


    /*
        人群部分。tab 人群
    */
    self_crowd_tab: '我的',
    group_crowd_tab: '运营组的',
    subordinate_crowd_tab: '下级的',
    // 新建人群
    create_crowd_button_self: '新建人群',
    create_crowd_button_group: '新建人群',
    create_crowd_button_subordinate: '新建人群',
    // 删除人群
    delete_crowd_button_self: '删除人群',
    delete_crowd_button_group: '删除人群',
    delete_crowd_button_subordinate: '删除人群',
    // 激活人群
    active_crowd_button_self: '激活人群',
    active_crowd_button_group: '激活人群',
    active_crowd_button_subordinate: '激活人群',
    // 冻结人群
    freeze_crowd_button_self: '冻结人群',
    freeze_crowd_button_group: '冻结人群',
    freeze_crowd_button_subordinate: '冻结人群',
    // 人群修改策略
    strategy_crowd_button_self: '修改策略',
    strategy_crowd_button_group: '修改策略',
    strategy_crowd_button_subordinate: '修改策略',
    // ...
    more_crowd_button_self: '更多操作',
    more_crowd_button_group: '更多操作',
    more_crowd_button_subordinate: '更多操作',
    // 人群描述
    des_crowd_button_self: '人群描述',
    des_crowd_button_group: '人群描述',
    des_crowd_button_subordinate: '人群描述',
    // 人群名称
    name_crowd_button_self: '人群名称',
    name_crowd_button_group: '人群名称',
    name_crowd_button_subordinate: '人群名称',
    // 人群所属目录
    catalog_crowd_cascader_self: '人群所属目录',
    catalog_crowd_cascader_group: '人群所属目录',
    catalog_crowd_cascader_subordinate: '人群所属目录',
    // 人群目录增，删，改
    catalog_tree_crowd_self: '人群新建目录',
    catalog_tree_crowd_group: '人群新建目录',
    catalog_tree_crowd_subordinate: '人群新建目录',
    // 人群重新计算按钮
    calc_crowd_button_self: '人群重新计算',
    calc_crowd_button_group: '人群重新计算',
    calc_crowd_button_subordinate: '人群重新计算'
};
